// ============================================================
// data.js — Product Catalog & App Configuration
// ============================================================

const APP_CONFIG = {
  name: "Nexus Store",
  currency: "₹",
  taxRate: 0.18,
  shipping: { standard: 49, express: 149, freeAbove: 999 },
};

const PRODUCTS = [
  {
    id: 1,
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    category: "Electronics",
    price: 29990,
    discount: 15,
    rating: 4.8,
    reviews: 3241,
    stock: 12,
    popularity: 98,
    daysOld: 45,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&q=80",
    description: "Industry-leading noise cancellation with 30-hour battery life. Crystal clear sound with LDAC support.",
    tags: ["wireless", "noise-cancelling", "premium"],
  },
  {
    id: 2,
    name: "Apple iPhone 15 Pro Max",
    brand: "Apple",
    category: "Electronics",
    price: 134900,
    discount: 5,
    rating: 4.9,
    reviews: 8102,
    stock: 5,
    popularity: 99,
    daysOld: 90,
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&q=80",
    description: "Titanium design, A17 Pro chip, and a pro camera system with 5× optical zoom.",
    tags: ["smartphone", "5G", "premium"],
  },
  {
    id: 3,
    name: "Samsung 55\" 4K QLED Smart TV",
    brand: "Samsung",
    category: "Electronics",
    price: 74990,
    discount: 20,
    rating: 4.6,
    reviews: 1892,
    stock: 8,
    popularity: 87,
    daysOld: 120,
    image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400&q=80",
    description: "Quantum Dot technology delivers 100% colour volume with Quantum HDR and Real Game Enhancer+.",
    tags: ["TV", "4K", "smart"],
  },
  {
    id: 4,
    name: "Dell XPS 15 Laptop",
    brand: "Dell",
    category: "Electronics",
    price: 149990,
    discount: 10,
    rating: 4.7,
    reviews: 2341,
    stock: 0,
    popularity: 91,
    daysOld: 60,
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80",
    description: "Intel Core i9, NVIDIA RTX 4060, 32GB RAM, 1TB SSD. The ultimate creator laptop.",
    tags: ["laptop", "gaming", "creator"],
  },
  {
    id: 5,
    name: "Canon EOS R6 Mark II",
    brand: "Canon",
    category: "Electronics",
    price: 229990,
    discount: 8,
    rating: 4.8,
    reviews: 987,
    stock: 4,
    popularity: 82,
    daysOld: 30,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
    description: "40fps burst shooting, 6K RAW video, with dual pixel CMOS AF II for professionals.",
    tags: ["camera", "mirrorless", "professional"],
  },
  {
    id: 6,
    name: "Levi's 511 Slim Fit Jeans",
    brand: "Levi's",
    category: "Fashion",
    price: 3999,
    discount: 25,
    rating: 4.4,
    reviews: 5621,
    stock: 50,
    popularity: 88,
    daysOld: 200,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&q=80",
    description: "Classic slim fit with just the right amount of stretch. Sits below the waist, slim through thigh and leg.",
    tags: ["jeans", "casual", "slim-fit"],
  },
  {
    id: 7,
    name: "Nike Air Max 270 Sneakers",
    brand: "Nike",
    category: "Fashion",
    price: 12995,
    discount: 0,
    rating: 4.6,
    reviews: 4312,
    stock: 30,
    popularity: 94,
    daysOld: 150,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    description: "Inspired by Air Max icons of the past, the Nike Air Max 270 delivers a lifestyle shoe with max comfort.",
    tags: ["shoes", "sneakers", "running"],
  },
  {
    id: 8,
    name: "Ray-Ban Aviator Classic Sunglasses",
    brand: "Ray-Ban",
    category: "Fashion",
    price: 9990,
    discount: 12,
    rating: 4.7,
    reviews: 2891,
    stock: 20,
    popularity: 89,
    daysOld: 300,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&q=80",
    description: "The iconic Aviator with classic teardrop lenses. UV400 protection, lightweight metal frame.",
    tags: ["sunglasses", "classic", "UV-protection"],
  },
  {
    id: 9,
    name: "Adidas Ultraboost 23 Running Shoes",
    brand: "Adidas",
    category: "Fashion",
    price: 17999,
    discount: 15,
    rating: 4.5,
    reviews: 3102,
    stock: 18,
    popularity: 90,
    daysOld: 80,
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&q=80",
    description: "Responsive BOOST midsole returns energy with every step. Primeknit+ upper adapts to your foot.",
    tags: ["running", "boost", "comfort"],
  },
  {
    id: 10,
    name: "Zara Trench Coat",
    brand: "Zara",
    category: "Fashion",
    price: 6990,
    discount: 30,
    rating: 4.3,
    reviews: 1543,
    stock: 0,
    popularity: 76,
    daysOld: 40,
    image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400&q=80",
    description: "Classic double-breasted trench coat with belt. Water-resistant fabric for all-season wear.",
    tags: ["coat", "winter", "classic"],
  },
  {
    id: 11,
    name: "IKEA KALLAX Shelf Unit",
    brand: "IKEA",
    category: "Home",
    price: 8999,
    discount: 0,
    rating: 4.5,
    reviews: 6743,
    stock: 25,
    popularity: 83,
    daysOld: 500,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80",
    description: "Versatile shelf unit with 8 compartments. Use with or without inserts for customisable storage.",
    tags: ["storage", "shelving", "modular"],
  },
  {
    id: 12,
    name: "Philips Air Fryer XXL",
    brand: "Philips",
    category: "Home",
    price: 12995,
    discount: 22,
    rating: 4.6,
    reviews: 4218,
    stock: 14,
    popularity: 92,
    daysOld: 180,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    description: "7L capacity, 2000W. Patented Twin TurboStar technology for evenly crispy results with 90% less fat.",
    tags: ["kitchen", "cooking", "healthy"],
  },
  {
    id: 13,
    name: "Dyson V15 Detect Cordless Vacuum",
    brand: "Dyson",
    category: "Home",
    price: 54900,
    discount: 10,
    rating: 4.8,
    reviews: 2103,
    stock: 9,
    popularity: 85,
    daysOld: 100,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    description: "Laser detects invisible dust. Scientifically validates your clean with LCD display.",
    tags: ["vacuum", "cordless", "smart"],
  },
  {
    id: 14,
    name: "Ceramic Non-Stick Cookware Set (10 Piece)",
    brand: "Prestige",
    category: "Home",
    price: 4599,
    discount: 35,
    rating: 4.4,
    reviews: 3891,
    stock: 32,
    popularity: 78,
    daysOld: 250,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80",
    description: "100% PFOA-free ceramic coating. Compatible with all stovetops including induction.",
    tags: ["cookware", "ceramic", "kitchen"],
  },
  {
    id: 15,
    name: "Smart LED Bulb (4-Pack)",
    brand: "Philips",
    category: "Home",
    price: 1499,
    discount: 0,
    rating: 4.3,
    reviews: 7231,
    stock: 100,
    popularity: 80,
    daysOld: 365,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    description: "16 million colours, voice control compatible with Alexa & Google Home. No hub required.",
    tags: ["smart home", "lighting", "IoT"],
  },
  {
    id: 16,
    name: "Atomic Habits by James Clear",
    brand: "Penguin",
    category: "Books",
    price: 499,
    discount: 40,
    rating: 4.9,
    reviews: 12431,
    stock: 200,
    popularity: 97,
    daysOld: 1800,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80",
    description: "Tiny changes, remarkable results. A proven framework for getting 1% better every day.",
    tags: ["self-help", "productivity", "bestseller"],
  },
  {
    id: 17,
    name: "The Psychology of Money",
    brand: "Jaico",
    category: "Books",
    price: 399,
    discount: 35,
    rating: 4.8,
    reviews: 9821,
    stock: 150,
    popularity: 95,
    daysOld: 1200,
    image: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=400&q=80",
    description: "Timeless lessons on wealth, greed, and happiness. By Morgan Housel.",
    tags: ["finance", "investing", "bestseller"],
  },
  {
    id: 18,
    name: "Deep Work by Cal Newport",
    brand: "Grand Central",
    category: "Books",
    price: 549,
    discount: 20,
    rating: 4.7,
    reviews: 6543,
    stock: 80,
    popularity: 88,
    daysOld: 2000,
    image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&q=80",
    description: "Rules for focused success in a distracted world. Master the rare ability to focus without distraction.",
    tags: ["productivity", "focus", "non-fiction"],
  },
  {
    id: 19,
    name: "Sapiens: A Brief History of Humankind",
    brand: "Harper",
    category: "Books",
    price: 699,
    discount: 25,
    rating: 4.8,
    reviews: 15321,
    stock: 120,
    popularity: 96,
    daysOld: 3000,
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80",
    description: "By Yuval Noah Harari. A groundbreaking narrative of humanity's creation and evolution.",
    tags: ["history", "science", "bestseller"],
  },
  {
    id: 20,
    name: "The Lean Startup",
    brand: "Crown Business",
    category: "Books",
    price: 599,
    discount: 0,
    rating: 4.5,
    reviews: 8231,
    stock: 0,
    popularity: 84,
    daysOld: 4000,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80",
    description: "How today's entrepreneurs use continuous innovation to create successful businesses.",
    tags: ["entrepreneurship", "startup", "business"],
  },
  {
    id: 21,
    name: "Yonex Badminton Racket Arcsaber 11",
    brand: "Yonex",
    category: "Sports",
    price: 8990,
    discount: 10,
    rating: 4.7,
    reviews: 1823,
    stock: 16,
    popularity: 82,
    daysOld: 200,
    image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400&q=80",
    description: "Carbon nanotube graphite frame for repulsion power. Ideal for intermediate to advanced players.",
    tags: ["badminton", "racket", "sports"],
  },
  {
    id: 22,
    name: "Decathlon Kiprun Running Shoes",
    brand: "Decathlon",
    category: "Sports",
    price: 2999,
    discount: 18,
    rating: 4.4,
    reviews: 4312,
    stock: 40,
    popularity: 79,
    daysOld: 100,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&q=80",
    description: "EVA foam midsole for cushioning. Breathable mesh upper for long-distance comfort.",
    tags: ["running", "sports", "footwear"],
  },
  {
    id: 23,
    name: "Fitbit Charge 6 Fitness Tracker",
    brand: "Fitbit",
    category: "Sports",
    price: 14999,
    discount: 12,
    rating: 4.5,
    reviews: 3102,
    stock: 22,
    popularity: 86,
    daysOld: 150,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&q=80",
    description: "Built-in GPS, 40+ exercise modes, heart rate, SpO2, ECG app, and stress management.",
    tags: ["fitness", "tracker", "smartwatch"],
  },
  {
    id: 24,
    name: "Cosco Football Size 5",
    brand: "Cosco",
    category: "Sports",
    price: 899,
    discount: 0,
    rating: 4.2,
    reviews: 2891,
    stock: 75,
    popularity: 71,
    daysOld: 600,
    image: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=400&q=80",
    description: "32-panel PVC football with butyl bladder for superior air retention. FIFA approved dimensions.",
    tags: ["football", "outdoor", "team-sport"],
  },
  {
    id: 25,
    name: "Boldfit Gym Gloves Pro",
    brand: "Boldfit",
    category: "Sports",
    price: 599,
    discount: 50,
    rating: 4.3,
    reviews: 6721,
    stock: 60,
    popularity: 75,
    daysOld: 400,
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&q=80",
    description: "Anti-slip silicone grip, breathable neoprene back, wrist support strap. Unisex.",
    tags: ["gym", "gloves", "fitness"],
  },
  {
    id: 26,
    name: "boAt Airdopes 141 TWS Earbuds",
    brand: "boAt",
    category: "Electronics",
    price: 1299,
    discount: 60,
    rating: 4.2,
    reviews: 18921,
    stock: 85,
    popularity: 96,
    daysOld: 180,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&q=80",
    description: "42H playtime, BEAST™ Mode for gaming, ENx™ technology for calls. IPX4 water resistance.",
    tags: ["earbuds", "wireless", "TWS"],
  },
  {
    id: 27,
    name: "Mi Smart Band 7",
    brand: "Xiaomi",
    category: "Electronics",
    price: 2999,
    discount: 20,
    rating: 4.4,
    reviews: 9821,
    stock: 50,
    popularity: 91,
    daysOld: 240,
    image: "https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=400&q=80",
    description: "1.62\" AMOLED display, 110+ workout modes, blood oxygen, 14-day battery life.",
    tags: ["smartband", "fitness", "Xiaomi"],
  },
  {
    id: 28,
    name: "Wildcraft 45L Hiking Backpack",
    brand: "Wildcraft",
    category: "Sports",
    price: 3499,
    discount: 22,
    rating: 4.5,
    reviews: 2341,
    stock: 35,
    popularity: 78,
    daysOld: 300,
    image: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=400&q=80",
    description: "Rain cover included. Padded shoulder straps, laptop sleeve, multiple compartments.",
    tags: ["backpack", "hiking", "travel"],
  },
];

// Categories and brands derived from products
const CATEGORIES = [...new Set(PRODUCTS.map((p) => p.category))].sort();
const BRANDS = [...new Set(PRODUCTS.map((p) => p.brand))].sort();

// Helper: get discounted price
function getDiscountedPrice(product) {
  return Math.round(product.price * (1 - product.discount / 100));
}

// Helper: get star HTML
function getStarHTML(rating) {
  const full = Math.floor(rating);
  const half = rating % 1 >= 0.5;
  let stars = "";
  for (let i = 0; i < full; i++) stars += "★";
  if (half) stars += "½";
  for (let i = full + (half ? 1 : 0); i < 5; i++) stars += "☆";
  return stars;
}
